language: python

install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install -e .

stages:
  - name: basic tests
    if: type = push OR type = pull_request
  - name: behind Earthdata
    if: branch = master OR commit_message =~ nsidc_tests OR type = cron

#ultimately move basic tests list into a separate script with the list of files to run (then this can be put into a matrix and parallellized as well)
jobs:
  include:
    - stage: basic tests
      script: pytest icepyx/ --ignore icepyx/tests/behind_NSIDC_API_login.py
      after_success: codecov

    # - stage: behind Earthdata
    #   script:
    #     - export NSIDC_LOGIN=$NSIDC_LOGIN
    #     - pytest icepyx/tests/behind_NSIDC_API_login.py

deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/ 
    username: "__token__"
    password: $test_PyPI_API_Token
    on:
      branch: development
      if: commit_message =~ test_pypi
    skip_existing: true
    distributions: "sdist bdist_wheel"
  - provider: pypi
    username: "__token__"
    password: $PyPI_API_Token
    on:
      branch: master
      tags: true
    skip_existing: true
    distributions: "sdist bdist_wheel"
